services:
  web:
    build: .
    container_name: petvax_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]

volumes:
  sqlite_data:
